/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp org.freedesktop.ModemManager1.Modem.Messaging.xml -p Messaging -N -i generic-types.h
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "Messaging.h"

/*
 * Implementation of interface class OrgFreedesktopModemManager1ModemMessagingInterface
 */

OrgFreedesktopModemManager1ModemMessagingInterface::OrgFreedesktopModemManager1ModemMessagingInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManager1ModemMessagingInterface::~OrgFreedesktopModemManager1ModemMessagingInterface()
{
}

