/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -p mm-modem-gsm-ussdinterface /home/ilia/libnm-qt/libmm-qt/dbus/introspection/mm-modem-gsm-ussd.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mm-modem-gsm-ussdinterface.h"

/*
 * Implementation of interface class OrgFreedesktopModemManagerModemGsmUssdInterface
 */

OrgFreedesktopModemManagerModemGsmUssdInterface::OrgFreedesktopModemManagerModemGsmUssdInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManagerModemGsmUssdInterface::~OrgFreedesktopModemManagerModemGsmUssdInterface()
{
}


#include "mm-modem-gsm-ussdinterface.moc"
