/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -p mm-modem-gsm-contactsinterface /home/ilia/libnm-qt/libmm-qt/dbus/introspection/mm-modem-gsm-contacts.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mm-modem-gsm-contactsinterface.h"

/*
 * Implementation of interface class OrgFreedesktopModemManagerModemGsmContactsInterface
 */

OrgFreedesktopModemManagerModemGsmContactsInterface::OrgFreedesktopModemManagerModemGsmContactsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManagerModemGsmContactsInterface::~OrgFreedesktopModemManagerModemGsmContactsInterface()
{
}


#include "mm-modem-gsm-contactsinterface.moc"
