/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m introspection/org.freedesktop.ModemManager1.Modem.Modem3gpp.xml -p mm-modem-modem3gppinterface
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mm-modem-modem3gppinterface.h"

/*
 * Implementation of interface class OrgFreedesktopModemManager1ModemModem3gppInterface
 */

OrgFreedesktopModemManager1ModemModem3gppInterface::OrgFreedesktopModemManager1ModemModem3gppInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManager1ModemModem3gppInterface::~OrgFreedesktopModemManager1ModemModem3gppInterface()
{
}


#include "mm-modem-modem3gppinterface.moc"
