/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m introspection/org.freedesktop.ModemManager1.Modem.Time.xml -p mm-modem-timeinterface
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MM-MODEM-TIMEINTERFACE_H_1370342125
#define MM-MODEM-TIMEINTERFACE_H_1370342125

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.ModemManager1.Modem.Time
 */
class OrgFreedesktopModemManager1ModemTimeInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.ModemManager1.Modem.Time"; }

public:
    OrgFreedesktopModemManager1ModemTimeInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopModemManager1ModemTimeInterface();

    Q_PROPERTY(QVariantMap NetworkTimezone READ networkTimezone)
    inline QVariantMap networkTimezone() const
    { return qvariant_cast< QVariantMap >(property("NetworkTimezone")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> GetNetworkTime()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetNetworkTime"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void NetworkTimeChanged(const QString &time);
};

namespace org {
  namespace freedesktop {
    namespace ModemManager1 {
      namespace Modem {
        typedef ::OrgFreedesktopModemManager1ModemTimeInterface Time;
      }
    }
  }
}
#endif
