/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m introspection/org.freedesktop.ModemManager1.Modem.Time.xml -p mm-modem-timeinterface
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mm-modem-timeinterface.h"

/*
 * Implementation of interface class OrgFreedesktopModemManager1ModemTimeInterface
 */

OrgFreedesktopModemManager1ModemTimeInterface::OrgFreedesktopModemManager1ModemTimeInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopModemManager1ModemTimeInterface::~OrgFreedesktopModemManager1ModemTimeInterface()
{
}


#include "mm-modem-timeinterface.moc"
